name: Build SnakeGame with Buildozer

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Accept Android SDK licenses
      run: |
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
        echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK_ROOT/licenses/android-sdk-preview-license"

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
